name: .NET

on:
  push:
    tags:
       - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: |
          export VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')
          echo $VERSION
          dotnet build --no-restore -c release
          dotnet pack --no-restore -c release -o ./publish -p:Version=$VERSION
    - name: Nuget Library Deploy
      uses: EasyDesk/job-nuget-library-deploy@v1.0.0
      with:
        dotnet-version: 6.x
        nuget-api-key: oy2hyiv5gjfjx6bm5jaafsltakdidbjezjndo6evrewkhq        
        publish-dir: ./publish

